name: Actions Workflow

on:
  push:
    branches:
      - main
      - 'feature/*' # matches feature/featA, feature/featB,
      # don't match feature/feat/something...
      - 'feature/**' #this will match all kind of variants which coming after 'feature/kissa/koira'
      - '!feature/featC' # ignore every branch which starts featur/featC
    tags:
      - v1.*
    paths:
      - '**.js'
      -
jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files Before
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{github.token}}"
      #          git clone git@github.com:$GITHUB_REPOSITORY
      #          git checkout $GITHUB_SHA
      - name: Checkout
        uses: /actions/checkout@v2
      - name: List Files After
        run: |
          pwd
          ls -a
      - name: Github Workspace
        run: echo $GITHUB_WORKSPACE
      - name: Simple JS Action
        uses: actions/hello-world-javascript-action@v1.1
        with:
          who-to-greet: John
      - name: Log Greeting Time
        run: echo "${{steps.greet.outputs.time}}"