name: Actions Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files Before
        run: |
          pwd
          ls -a
      - name: Checkout
        uses: /actions/checkout@v2
      - name: List Files After
        run: |
            pwd
          ls -a
      - name: Github Workspace
        run: echo $GITHUB_WORKSPACE
      - name: Simple JS Action
        uses: actions/hello-world-javascript-action@v1.1
        with:
          who-to-greet: John
      - name: Log Greeting Time
        run: echo "${{steps.greet.outputs.time}}"