name: CI TEST
on:
  pull_request:
    branches:
      - main

jobs:
  test-semantic-release-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: List Files After
        run: |
          pwd
          ls -a
      - name: Create A Semantic Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}