name: CI
on:
  pull_request:
    branches:
      - main

jobs:
  test-semantic-release-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: List Files After
        run: |
          pwd
          ls -a
